import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { TopicMap, validateBank, type BankIssue } from './bank';
import { buildBank, selectAppBank, serializeCanonical, unresolvedCheckpointBankRefs } from './build';
import { ContentPackSchema } from './schema';
import {
  ALT_TEXT_PENDING_NEEDLE,
  carRowToQuestion,
  vmcRowToQuestion,
  type Cells,
} from './ingest';
import type { BankQuestion } from './bank';
import { readXlsxSheet1 } from './xlsx';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const BANK_DIR = join(ROOT, 'content/bank');
const SOURCES_PATH = join(BANK_DIR, 'sources.json');
const CAR_BANK_PATH = join(BANK_DIR, 'car-b.json');
const VMC_BANK_PATH = join(BANK_DIR, 'vmc.json');
const ALT_TEXT_PATH = join(BANK_DIR, 'alt-text.json');
const TOPIC_MAP_PATH = join(ROOT, 'content/topic-map.json');
const ASSET_BANK_DIR = join(ROOT, 'apps/mobile/assets/bank');
// Generated require map so Metro bundles the licensed gifs offline (git-excluded, tripwire 7);
// the tracked src/content/bankAssets.ts loader require()s it. Mirrors the bank.json pipeline.
const ASSET_MAP_PATH = join(ASSET_BANK_DIR, 'assetMap.js');
// The app-facing pool bank the mobile app bundles — licensed, git-excluded (tripwire 7),
// built from the two source banks. Mirrors the pack.json pipeline.
const GENERATED_BANK_PATH = join(ROOT, 'apps/mobile/src/content/generated/bank.json');
// The tracked content pack — its missions may carry curated checkpoint bankRefs (vB.4).
const PACK_PATH = join(ROOT, 'apps/mobile/src/content/generated/pack.json');

// Verified against the February 2026 material. A future update that changes these bumps the
// constant (a mismatch fails loudly rather than silently shipping a short bank).
const EXPECTED_CAR = 758;
const EXPECTED_VMC = 27;

interface Sources {
  carXlsx: string;
  carGifsDir: string;
  vmcXlsx: string;
}

function loadTopicMap(): TopicMap {
  return TopicMap.parse(JSON.parse(readFileSync(TOPIC_MAP_PATH, 'utf8')));
}

function walkFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walkFiles(full));
    else out.push(full);
  }
  return out;
}

function isReal(e: BankIssue): boolean {
  return !e.message.includes(ALT_TEXT_PENDING_NEEDLE);
}

function loadAltText(): Record<string, string> {
  return existsSync(ALT_TEXT_PATH)
    ? (JSON.parse(readFileSync(ALT_TEXT_PATH, 'utf8')) as Record<string, string>)
    : {};
}

function dataRows(sheet: Cells[]): Cells[] {
  return sheet.slice(2).filter((r) => r.A && r.A.trim());
}

function sheetTitle(sheet: Cells[], fallback: string): string {
  return sheet[0]?.A?.trim() || fallback;
}

// Byte-stable per-question canonical form, so "changed" compares content not key order.
function diffSummary(path: string, questions: BankQuestion[]): string {
  if (!existsSync(path)) return 'new bank';
  const prev = JSON.parse(readFileSync(path, 'utf8')) as { questions: { item: string }[] };
  const prevMap = new Map(prev.questions.map((q) => [q.item, serializeCanonical(q)]));
  const nextMap = new Map(questions.map((q) => [q.item, serializeCanonical(q)]));
  let added = 0;
  let removed = 0;
  let changed = 0;
  for (const [item, form] of nextMap) {
    if (!prevMap.has(item)) added += 1;
    else if (prevMap.get(item) !== form) changed += 1;
  }
  for (const item of prevMap.keys()) if (!nextMap.has(item)) removed += 1;
  return `${added} added, ${removed} removed, ${changed} changed (was ${prev.questions.length})`;
}

function optionImages(questions: BankQuestion[]): string[] {
  const set = new Set<string>();
  for (const q of questions) for (const o of q.options) if (o.imageRef) set.add(o.imageRef);
  return [...set].sort();
}

// A deterministic CommonJS require map so Metro bundles each licensed gif offline. Sorted for
// byte-stable re-runs; loaded by the tracked src/content/bankAssets.ts require() loader.
function serializeAssetMap(referenced: Set<string>): string {
  const lines = [...referenced]
    .sort()
    .map((name) => `  ${JSON.stringify(name)}: require(${JSON.stringify('./' + name)}),`);
  return (
    '// GENERATED by `pnpm content ingest` — licensed asset require map, git-excluded.\n' +
    `module.exports = {\n${lines.join('\n')}\n};\n`
  );
}

function fail(problems: string[]): never {
  for (const p of problems) console.error(`ERROR ${p}`);
  console.error(`\ningest aborted — ${problems.length} problem(s), no output written`);
  process.exit(1);
}

export function runIngest(): void {
  if (!existsSync(SOURCES_PATH)) {
    console.error(`error: no source config at ${relative(ROOT, SOURCES_PATH)}`);
    console.error('  the ingest runs only where the licensed source material is present.');
    console.error('  create it with { "carXlsx", "carGifsDir", "vmcXlsx" } (paths relative to repo root).');
    process.exit(1);
  }
  const sources = JSON.parse(readFileSync(SOURCES_PATH, 'utf8')) as Sources;
  const topicMap = loadTopicMap();
  const altText = loadAltText();

  const gifIndex = new Map<string, string>();
  for (const abs of walkFiles(join(ROOT, sources.carGifsDir))) {
    if (abs.toLowerCase().endsWith('.gif')) gifIndex.set(abs.split('/').pop()!, abs);
  }
  const availableImages = new Set(gifIndex.keys());

  const carSheet = readXlsxSheet1(readFileSync(join(ROOT, sources.carXlsx)));
  const carRows = dataRows(carSheet);
  const carQuestions = carRows.map((r) => carRowToQuestion(r, topicMap, altText));
  const carBank = { bankFormat: 1 as const, source: sheetTitle(carSheet, 'Car question bank'), questions: carQuestions };

  const vmcSheet = readXlsxSheet1(readFileSync(join(ROOT, sources.vmcXlsx)));
  const vmcRows = dataRows(vmcSheet);
  const vmcQuestions = vmcRows.map(vmcRowToQuestion);
  const vmcBank = { bankFormat: 1 as const, source: sheetTitle(vmcSheet, 'Video question bank'), questions: vmcQuestions };

  const problems: string[] = [];
  if (carRows.length !== EXPECTED_CAR) {
    problems.push(`expected ${EXPECTED_CAR} car questions, mapped ${carRows.length}`);
  }
  if (vmcRows.length !== EXPECTED_VMC) {
    problems.push(`expected ${EXPECTED_VMC} video questions, mapped ${vmcRows.length}`);
  }

  const carReport = validateBank(carBank, topicMap, { images: availableImages });
  const pending = carReport.errors.filter((e) => !isReal(e));
  for (const e of carReport.errors.filter(isReal)) problems.push(`car ${e.where}: ${e.message}`);

  const vmcReport = validateBank(vmcBank, topicMap, { videoBank: true });
  for (const e of vmcReport.errors) problems.push(`vmc ${e.where}: ${e.message}`);

  if (problems.length) fail(problems);

  // Everything validated — now write. Diffs are computed before the files are overwritten.
  const carDiff = diffSummary(CAR_BANK_PATH, carQuestions);
  const vmcDiff = diffSummary(VMC_BANK_PATH, vmcQuestions);

  mkdirSync(BANK_DIR, { recursive: true });
  writeFileSync(CAR_BANK_PATH, serializeCanonical(carBank), 'utf8');
  writeFileSync(VMC_BANK_PATH, serializeCanonical(vmcBank), 'utf8');

  mkdirSync(ASSET_BANK_DIR, { recursive: true });
  const referenced = new Set<string>();
  for (const q of carQuestions) {
    if (q.stemImage) referenced.add(q.stemImage);
    for (const o of q.options) if (o.imageRef) referenced.add(o.imageRef);
  }
  for (const name of referenced) copyFileSync(gifIndex.get(name)!, join(ASSET_BANK_DIR, name));
  writeFileSync(ASSET_MAP_PATH, serializeAssetMap(referenced), 'utf8');

  const files = optionImages(carQuestions);
  const skeleton: Record<string, string> = {};
  for (const name of files) skeleton[name] = altText[name] ?? '';
  writeFileSync(ALT_TEXT_PATH, serializeCanonical(skeleton), 'utf8');
  const authored = files.filter((n) => skeleton[n]).length;

  const poolCount = writeGeneratedBank(carBank, vmcBank);

  console.log(`car-b.json: ${carQuestions.length} questions — ${carDiff}`);
  console.log(`vmc.json:   ${vmcQuestions.length} questions — ${vmcDiff}`);
  console.log(`gifs:       ${referenced.size} bundled → ${relative(ROOT, ASSET_BANK_DIR)}`);
  console.log(
    `alt-text:   ${files.length} option-image files (${authored} authored), ` +
      `${pending.length} questions pending alt-text (author in vB.3)`,
  );
  console.log(`app bank:   ${poolCount} pool questions → ${relative(ROOT, GENERATED_BANK_PATH)}`);
}

// Write the app-facing pool bank (car-eligible + video) the mobile app bundles. Excluded
// from git (tripwire 7); regenerated deterministically from the two source banks.
function writeGeneratedBank(rawCarFile: unknown, rawVmcFile: unknown): number {
  const appBank = selectAppBank(rawCarFile, rawVmcFile);
  mkdirSync(dirname(GENERATED_BANK_PATH), { recursive: true });
  writeFileSync(GENERATED_BANK_PATH, serializeCanonical(appBank), 'utf8');
  return appBank.questions.length;
}

// CLI `bank-build`: rebuild only the app pool bank from the on-disk source banks (no xlsx
// re-parse). Useful after alt-text authoring (vB.3) without a full re-ingest.
export function bankBuild(): void {
  if (!existsSync(CAR_BANK_PATH)) {
    console.error(
      `error: no ingested bank at ${relative(ROOT, CAR_BANK_PATH)} — run pnpm content ingest first`,
    );
    process.exit(1);
  }
  const car = JSON.parse(readFileSync(CAR_BANK_PATH, 'utf8'));
  const vmc = existsSync(VMC_BANK_PATH) ? JSON.parse(readFileSync(VMC_BANK_PATH, 'utf8')) : undefined;
  const n = writeGeneratedBank(car, vmc);
  console.log(`app bank: ${n} pool questions → ${relative(ROOT, GENERATED_BANK_PATH)}`);
}

// Gate hook: when a bank has been ingested locally, re-validate it so a stale or hand-edited
// bank fails the gate. No-op on a clean clone (no content/bank/), where the material is absent.
export function checkBank(): void {
  if (!existsSync(CAR_BANK_PATH)) return;
  const topicMap = loadTopicMap();
  const images = existsSync(ASSET_BANK_DIR)
    ? new Set(readdirSync(ASSET_BANK_DIR).filter((f) => f.toLowerCase().endsWith('.gif')))
    : undefined;

  const carBank = JSON.parse(readFileSync(CAR_BANK_PATH, 'utf8')) as { questions: unknown[] };
  const carReport = validateBank(carBank, topicMap, images ? { images } : {});
  const real = carReport.errors.filter(isReal);
  const pending = carReport.errors.length - real.length;

  const problems = real.map((e) => `car ${e.where}: ${e.message}`);
  let vmcCount = 0;
  if (existsSync(VMC_BANK_PATH)) {
    const vmcBank = JSON.parse(readFileSync(VMC_BANK_PATH, 'utf8')) as { questions: unknown[] };
    vmcCount = vmcBank.questions.length;
    for (const e of validateBank(vmcBank, topicMap, { videoBank: true }).errors) {
      problems.push(`vmc ${e.where}: ${e.message}`);
    }
  }

  if (problems.length) {
    for (const p of problems) console.error(`ERROR bank ${p}`);
    console.error('bank is invalid — re-run pnpm content ingest');
    process.exit(1);
  }
  console.log(
    `bank check: car ${carBank.questions.length} + vmc ${vmcCount} questions valid ` +
      `(${pending} pending alt-text)`,
  );
}

// Gate hook: when a bank has been ingested locally, a hand-edited source bank or a
// forgotten `bank-build` leaves the bundled app bank stale — fail loudly. No-op on a
// clean clone (no content/bank/), where the material is absent.
export function checkAppBank(): void {
  if (!existsSync(CAR_BANK_PATH)) return;
  const car = JSON.parse(readFileSync(CAR_BANK_PATH, 'utf8'));
  const vmc = existsSync(VMC_BANK_PATH) ? JSON.parse(readFileSync(VMC_BANK_PATH, 'utf8')) : undefined;
  const bytes = buildBank(car, vmc);
  const existing = existsSync(GENERATED_BANK_PATH)
    ? readFileSync(GENERATED_BANK_PATH, 'utf8')
    : undefined;
  if (existing !== bytes) {
    console.error('app bank is stale — run pnpm content bank-build');
    process.exit(1);
  }
  const n = (JSON.parse(bytes) as { questions: unknown[] }).questions.length;
  console.log(`app bank check: ${n} pool questions up to date`);
}

// Gate hook: resolve every curated checkpoint bankRef in the built pack against the app POOL
// bank — exactly what the app resolves against at runtime, so a ref pointing at a question the
// pool dropped (e.g. still awaiting alt-text) fails here, not on a device. No-op on a clean
// clone (no content/bank/) or before any pack is built.
export function checkPackBankRefs(): void {
  if (!existsSync(CAR_BANK_PATH) || !existsSync(PACK_PATH)) return;
  const pack = ContentPackSchema.parse(JSON.parse(readFileSync(PACK_PATH, 'utf8')));
  const missions = pack.routes.flatMap((r) => r.missions);
  const car = JSON.parse(readFileSync(CAR_BANK_PATH, 'utf8'));
  const vmc = existsSync(VMC_BANK_PATH) ? JSON.parse(readFileSync(VMC_BANK_PATH, 'utf8')) : undefined;
  const unresolved = unresolvedCheckpointBankRefs(missions, selectAppBank(car, vmc));
  if (unresolved.length) {
    for (const u of unresolved) {
      console.error(`ERROR bankRef ${u.missionId} ${u.stepId}#q${u.index}: "${u.bankRef}" not in the bank`);
    }
    console.error('checkpoint bankRefs do not resolve — fix the ref or re-ingest the bank');
    process.exit(1);
  }
  let refCount = 0;
  for (const m of missions) {
    for (const step of m.steps) {
      if (step.type === 'checkpoint') refCount += step.questions.filter((q) => 'bankRef' in q).length;
    }
  }
  console.log(`bankRef check: ${refCount} checkpoint bankRefs resolve`);
}
